---
language: go

git:
  depth: false

go:
  - stable

before_install:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  # - go test -race -coverprofile=coverage.txt -covermode=atomic
  - ginkgo -reportFile junit-report.xml -cover
  - sonar-scanner

addons:
  sonarcloud:
    organization: "dlresende"
